services:
  dawakahana-mis:
    build: .
    container_name: dawakahana-mis
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - mysql
    networks:
      - dawakahana-network

  mysql:
    image: mysql:8.4
    container_name: dawakahana-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dawakahana-network

volumes:
  mysql_data:

networks:
  dawakahana-network:
    driver: bridge
