"""empty message

Revision ID: 40fe134eacfd
Revises: 58773ef2903c
Create Date: 2026-08-14 18:11:04.803177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40fe134eacfd'
down_revision = '58773ef2903c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('transaction_type', sa.Enum('SALE', 'PURCHASE', 'PAYMENT', 'RETURN', 'ADJUSTMENT', name='transactiontype'), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('stock_movements')
    op.drop_table('customer_transactions')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('invoice_type',
               existing_type=mysql.ENUM('PURCHASE', 'SALE', 'RETURN'),
               type_=sa.Enum('PURCHASE', 'SALE', 'PURCHASE_RETURN', 'SALE_RETURN', name='invoicetype'),
               existing_nullable=False)
        batch_op.alter_column('payment_status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('PAID', 'PARTIAL', 'UNPAID', name='paymentstatus'),
               existing_nullable=True)
        batch_op.drop_column('paid_amount')
        batch_op.drop_column('remaining_amount')
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('remaining_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('paid_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.alter_column('payment_status',
               existing_type=sa.Enum('PAID', 'PARTIAL', 'UNPAID', name='paymentstatus'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('invoice_type',
               existing_type=sa.Enum('PURCHASE', 'SALE', 'PURCHASE_RETURN', 'SALE_RETURN', name='invoicetype'),
               type_=mysql.ENUM('PURCHASE', 'SALE', 'RETURN'),
               existing_nullable=False)

    op.create_table('customer_transactions',
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('invoice_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction_type', mysql.ENUM('SALE', 'PAYMENT', 'RETURN'), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', mysql.ENUM('CASH', 'CARD', 'TRANSFER'), nullable=True),
    sa.Column('note', mysql.TEXT(), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('customer_transactions_ibfk_1')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('customer_transactions_ibfk_2')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('customer_transactions_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('stock_movements',
    sa.Column('medicine_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stock_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('movement_type', mysql.ENUM('PURCHASE', 'SALE', 'RETURN', 'ADJUSTMENT', 'EXPIRED'), nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reference_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', mysql.TEXT(), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('stock_movements_ibfk_1')),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], name=op.f('stock_movements_ibfk_2')),
    sa.ForeignKeyConstraint(['stock_id'], ['medicine_stock.id'], name=op.f('stock_movements_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('transactions')
    # ### end Alembic commands ###
