"""empty message

Revision ID: 532e78e2bdc8
Revises: 9693f10508c7
Create Date: 2026-08-19 15:14:35.399440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '532e78e2bdc8'
down_revision = '9693f10508c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('invoices_ibfk_4'), type_='foreignkey')
        batch_op.drop_column('source_invoice_id')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_invoice_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'invoices', ['source_invoice_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('source_invoice_id')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_invoice_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('invoices_ibfk_4'), 'invoices', ['source_invoice_id'], ['id'])

    # ### end Alembic commands ###
