"""empty message

Revision ID: 62c0b3b3c383
Revises: 747f32300b14
Create Date: 2026-08-17 10:52:23.142587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62c0b3b3c383'
down_revision = '747f32300b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('DRAFT', 'COMPLETED', 'CANCELLED', name='invoicestatus'), nullable=False))
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', mysql.ENUM('PAID', 'PARTIAL', 'UNPAID'), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
