"""empty message

Revision ID: 747f32300b14
Revises: 40fe134eacfd
Create Date: 2026-08-15 14:08:09.865707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '747f32300b14'
down_revision = '40fe134eacfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('transaction_type',
               existing_type=mysql.ENUM('SALE', 'PURCHASE', 'PAYMENT', 'RETURN', 'ADJUSTMENT'),
               type_=sa.Enum('SALE', 'PURCHASE', 'PAYMENT', 'PURCHASE_RETURN', 'SALE_RETURN', 'ADJUSTMENT', name='transactiontype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('transaction_type',
               existing_type=sa.Enum('SALE', 'PURCHASE', 'PAYMENT', 'PURCHASE_RETURN', 'SALE_RETURN', 'ADJUSTMENT', name='transactiontype'),
               type_=mysql.ENUM('SALE', 'PURCHASE', 'PAYMENT', 'RETURN', 'ADJUSTMENT'),
               existing_nullable=False)

    # ### end Alembic commands ###
