"""empty message

Revision ID: 8ec4f5c8c9be
Revises: 62c0b3b3c383
Create Date: 2026-08-19 11:01:46.087673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ec4f5c8c9be'
down_revision = '62c0b3b3c383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('invoice_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('transaction_type',
               existing_type=mysql.ENUM('SALE', 'PURCHASE', 'PAYMENT', 'PURCHASE_RETURN', 'SALE_RETURN', 'ADJUSTMENT'),
               type_=sa.Enum('SALE', 'PURCHASE', 'PAYMENT', 'PURCHASE_RETURN', 'SALE_RETURN', 'ADJUSTMENT', 'CREDIT_USED', name='transactiontype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('transaction_type',
               existing_type=sa.Enum('SALE', 'PURCHASE', 'PAYMENT', 'PURCHASE_RETURN', 'SALE_RETURN', 'ADJUSTMENT', 'CREDIT_USED', name='transactiontype'),
               type_=mysql.ENUM('SALE', 'PURCHASE', 'PAYMENT', 'PURCHASE_RETURN', 'SALE_RETURN', 'ADJUSTMENT'),
               existing_nullable=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('invoice_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
