"""empty message

Revision ID: 9693f10508c7
Revises: 97092e62a504
Create Date: 2026-08-19 15:12:52.943296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9693f10508c7'
down_revision = '97092e62a504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_invoice_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'invoices', ['source_invoice_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('source_invoice_id')

    # ### end Alembic commands ###
