"""empty message

Revision ID: 97092e62a504
Revises: 8ec4f5c8c9be
Create Date: 2026-08-19 12:49:37.756055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97092e62a504'
down_revision = '8ec4f5c8c9be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('transaction_type',
               existing_type=mysql.ENUM('SALE', 'PURCHASE', 'PAYMENT', 'PURCHASE_RETURN', 'SALE_RETURN', 'ADJUSTMENT', 'CREDIT_USED'),
               type_=sa.Enum('SALE', 'PURCHASE', 'PAYMENT', 'REFUND', 'PURCHASE_RETURN', 'SALE_RETURN', 'CREDIT_USED', 'ADJUSTMENT', name='transactiontype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('transaction_type',
               existing_type=sa.Enum('SALE', 'PURCHASE', 'PAYMENT', 'REFUND', 'PURCHASE_RETURN', 'SALE_RETURN', 'CREDIT_USED', 'ADJUSTMENT', name='transactiontype'),
               type_=mysql.ENUM('SALE', 'PURCHASE', 'PAYMENT', 'PURCHASE_RETURN', 'SALE_RETURN', 'ADJUSTMENT', 'CREDIT_USED'),
               existing_nullable=False)

    # ### end Alembic commands ###
