from app.config import Config

PROJECT_TITLE: str = Config.PROJECT_TITLE
CURRENCY_SYMBOL: str = Config.CURRENCY_SYMBOL
DEFAULT_AVATAR: str = Config.DEFAULT_AVATAR
APP_DIR: str = Config.APP_DIR

ADMINISTER = Config.ADMINISTER
DEVELOPER = Config.DEVELOPER


ADMINISTRATOR = Config.ROLE["ADMINISTRATOR"]
EMPLOYEE = Config.ROLE["EMPLOYEE"]
LANGUAGES = ["en", "fa", "ps"]

FLASKY_ADMIN = Config.FLASKY_ADMIN
